# Generated by Django 5.2 on 2025-05-04 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schooluser',
            name='username',
        ),
    ]
