# Generated by Django 5.2 on 2025-05-04 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_schooluser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schooluser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
