# Generated by Django 5.2 on 2025-05-08 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_schooluser_is_moderator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schooluser',
            name='is_moderator',
        ),
    ]
