# Generated by Django 5.2 on 2025-04-23 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images_courses/'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images_lessons/'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='link',
            field=models.TextField(blank=True, null=True, verbose_name='Ссылка на видео'),
        ),
    ]
